-- =====================================================
-- Testes Estruturais - Validação das Estruturas
-- =====================================================

-- 1. VERIFICAR EXISTÊNCIA DAS TABELAS
SELECT
    'Verificação de Tabelas' as Teste,
    TABLE_NAME as Nome,
    TABLE_TYPE as Tipo,
    ENGINE as Motor
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME IN ('DIM_TEMPO', 'DIM_CLIENTE', 'DIM_PRODUTO', 'DIM_CANAL_VENDA', 'DIM_PROMOCAO', 'FATO_VENDAS')
ORDER BY TABLE_NAME;

-- 2. VERIFICAR COLUNAS DAS DIMENSÕES
SELECT
    'Colunas DIM_TEMPO' as Teste,
    COLUMN_NAME as Coluna,
    DATA_TYPE as Tipo,
    IS_NULLABLE as Nulo,
    COLUMN_KEY as Chave
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'DIM_TEMPO'
ORDER BY ORDINAL_POSITION;

-- 3. VERIFICAR ÍNDICES
SELECT
    'Índices Criados' as Teste,
    TABLE_NAME as Tabela,
    INDEX_NAME as Índice,
    COLUMN_NAME as Coluna,
    NON_UNIQUE as Não_Único
FROM INFORMATION_SCHEMA.STATISTICS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME IN ('DIM_TEMPO', 'DIM_CLIENTE', 'DIM_PRODUTO', 'DIM_CANAL_VENDA', 'DIM_PROMOCAO', 'FATO_VENDAS')
ORDER BY TABLE_NAME, INDEX_NAME, SEQ_IN_INDEX;

-- 4. VERIFICAR CONSTRAINTS DE CHAVE ESTRANGEIRA
SELECT
    'Foreign Keys' as Teste,
    CONSTRAINT_NAME as 'Constraint',
    TABLE_NAME as Tabela_Origem,
    COLUMN_NAME as Coluna_Origem,
    REFERENCED_TABLE_NAME as Tabela_Destino,
    REFERENCED_COLUMN_NAME as Coluna_Destino
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE TABLE_SCHEMA = DATABASE()
  AND REFERENCED_TABLE_NAME IS NOT NULL
ORDER BY TABLE_NAME, CONSTRAINT_NAME;

-- 5. VERIFICAR TAMANHO DAS TABELAS
SELECT
    'Tamanho das Tabelas' as Teste,
    TABLE_NAME as Tabela,
    TABLE_ROWS as Linhas,
    ROUND(((DATA_LENGTH + INDEX_LENGTH) / 1024 / 1024), 2) as Tamanho_MB
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME IN ('DIM_TEMPO', 'DIM_CLIENTE', 'DIM_PRODUTO', 'DIM_CANAL_VENDA', 'DIM_PROMOCAO', 'FATO_VENDAS')
ORDER BY Tamanho_MB DESC;
